citations = ["_- Qui que vous soyez, attention, cette fréquence est exclusivement réservée aux urgences.- Sans blague ! Et vous croyez que j'appelle pour commander une pizza ?_ **Piège de cristal, une opératrice et John McClane.**", 
"_- Bonjour ! - Bonjour ! - Ah ! Et au cas où on ne se reverrait pas, une bonne soirée et une excellente nuit !_ **The Truman show, Truman et un voisin.**",
 "_C'est seulement quand on a tout perdu qu'on est libre de faire tout ce qu'on veut._ **Fight Club, Tyler.**",
 "_Lorsqu'on n'a rien, on n'a rien à perdre._ **Titanic, Jack.**",
 "_Je rêve de vastes chiotes, impeccablement entretenues, avec des robinets plaqués or, du marbre blanc immaculé, un siège en ébène, une cuvette pleine de Channel nº5. Et un larbin qui me tend un rouleau de PQ en soie sauvage, mais vu l'urgence, j'irais n'importe où._ **Trainspotting, Renton.**",
 "_Je préfère être sa putain que votre femme._ **Titanic.**",
 "_- À l'arrivée du bateau, je m'enfuirai avec toi. - C'est de la folie ! - Oui je sais. C'est vraiment insensé. C'est pour ça que j'y crois._ **Titanic, Jack et Rose.**",
 "_- Disneyland aussi a eu quelques difficultés à ses débuts ! - Oui mais, John, quand les pirates des Caraïbes se détraquaient, ils ne dévoraient pas les touristes !_ **Jurassic park.**",
 "_- Dieu crée les dinosaures. Dieu détruit les dinosaures. Dieu crée l'homme. L'homme détruit Dieu. L'homme crée les dinosaures…- Les dinosaures mangent l'homme. Et la femme hérite de la Terre._ **Jurassic park.**",
 "_- Les suisses font ça pour se motiver au départ !- C'est pas une raison ! Ils fabriquent aussi des couteaux on… on va pas tout faire comme eux !_ **Rasta rockett.**",
 "_Heu… Encore une fois, comment êtes-vous sûr que ce ne sont que des femelles ? L'un de vous se promène dans le parc et soulève les jupes des dinosaures ?_ **Jurassic park.**",
 "_On laisse pas Bébé dans un coin_ **Dirty Dancing**",
 "_- Putain le con, j'ai buté Marvin ! - Mais pourquoi t'as fait ça ? - J'sais pas c'est un accident !_ Pulp Fiction, Vincent et Jules.**",
 "_- Tu n'es pas toi, tu es moi.- Sans blague…_ **Total recall, Hauser et Douglas Quaid.**",
 "_Qu'est ce que j'avais dit ? J'avais dit mollo sur le Destroy !_ **Peut-être**",
 "_C'est l'histoire d'un homme qui tombe d'un immeuble de cinquante étages. Le mec, au fur et à mesure de sa chute se répète sans cesse pour se rassurer : jusqu'ici tout va bien, jusqu'ici tout va bien, jusqu'ici tout va bien. Mais l'important c'est pas la chute, c'est l'atterrissage._ **La haine**",
 "_Vous savez bien, fish, chips, tasse de thé, bouffe dégueu, temps de merde, Mary Poppins de mes deux… Londres !_ **Snatch, Avi.**",
 "_La vie c'est comme une boîte de chocolats, on ne sait jamais sur quoi on va tomber._ **Forrest Gump, Forrest Gump.**",
 "_- Que vous est-il arrivé ? - Je suis pas fini._ **Edward aux mains d'argent**",
 "_La route ? Là où on va, on n'a pas besoin de route !_ **Retour vers le futur, Dr. Emmett Brown.**",
 "_Mon père lui a fait une offre qu'il ne pouvait pas refuser._ **Le parrain, Michael Corleone.**",
 "_Ma mère avait pour nom Gwendoline, elle est morte dévorée par les loups… parce que notre père qu'était parti pour boire à la taverne de Duchenot a crevé gelé dans l'étang à cause de son pied-bot. C'est diiiiingue nan ?_ **Les visiteurs, Jacquouille.**",
 "_- Tu l'aimes ta plante hein ! - C'est ma meilleure amie. Toujours de bonne humeur, jamais de questions… Et puis, elle est comme moi tu vois, pas de racines._ **Léon.**",
 "_Béni soit le Seigneur : ma force qui mène mes mains à la guerre et mes doigts au combat ; ma miséricorde et ma forteresse ; mon donjon et mon libérateur ; mon bouclier, celui en qui je donne ma foi._ **Il faut sauver le soldat Ryan, Daniel Jackson.**",
 "_- Je t'aime. - Idem._ **Ghost, Molly et Sam**"
 ]
